server:
  port: 8081
  servlet:
    context-path:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: KSCT
    password: KSCT1234

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.KSCT.work.model
  mapper-locations: mybatis/mapper/**/*.xml